# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mavProxyLink.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mavProxyLink.proto',
  package='mav',
  syntax='proto2',
  serialized_pb=_b('\n\x12mavProxyLink.proto\x12\x03mav\"\xb1\x01\n\x08\x41ircraft\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lon\x18\x02 \x02(\x01\x12\x0f\n\x07\x62\x65\x61ring\x18\x03 \x02(\x01\x12\r\n\x05speed\x18\x04 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x02(\x01\x12\x12\n\nwind_speed\x18\x06 \x02(\x01\x12\x16\n\x0ewind_direction\x18\x07 \x02(\x01\x12\x15\n\rmotor_current\x18\x08 \x02(\x01\x12\x16\n\x0emotor_throttle\x18\t \x02(\x01\",\n\tWaypoints\x12\x1f\n\x08waypoint\x18\x01 \x03(\x0b\x32\r.mav.Waypoint\"S\n\x08Waypoint\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lon\x18\x02 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x02(\x01\x12\r\n\x05speed\x18\x04 \x02(\x01\x12\x0c\n\x04type\x18\x05 \x02(\x05\"S\n\x0c\x41ircraftLink\x12 \n\taircrafts\x18\x01 \x03(\x0b\x32\r.mav.Aircraft\x12!\n\twaypoints\x18\x02 \x03(\x0b\x32\x0e.mav.Waypoints')
)




_AIRCRAFT = _descriptor.Descriptor(
  name='Aircraft',
  full_name='mav.Aircraft',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='mav.Aircraft.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='mav.Aircraft.lon', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bearing', full_name='mav.Aircraft.bearing', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='mav.Aircraft.speed', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='mav.Aircraft.altitude', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='mav.Aircraft.wind_speed', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='mav.Aircraft.wind_direction', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_current', full_name='mav.Aircraft.motor_current', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_throttle', full_name='mav.Aircraft.motor_throttle', index=8,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=205,
)


_WAYPOINTS = _descriptor.Descriptor(
  name='Waypoints',
  full_name='mav.Waypoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='mav.Waypoints.waypoint', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=251,
)


_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='mav.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='mav.Waypoint.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='mav.Waypoint.lon', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='mav.Waypoint.altitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='mav.Waypoint.speed', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='mav.Waypoint.type', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=336,
)


_AIRCRAFTLINK = _descriptor.Descriptor(
  name='AircraftLink',
  full_name='mav.AircraftLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aircrafts', full_name='mav.AircraftLink.aircrafts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='mav.AircraftLink.waypoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=421,
)

_WAYPOINTS.fields_by_name['waypoint'].message_type = _WAYPOINT
_AIRCRAFTLINK.fields_by_name['aircrafts'].message_type = _AIRCRAFT
_AIRCRAFTLINK.fields_by_name['waypoints'].message_type = _WAYPOINTS
DESCRIPTOR.message_types_by_name['Aircraft'] = _AIRCRAFT
DESCRIPTOR.message_types_by_name['Waypoints'] = _WAYPOINTS
DESCRIPTOR.message_types_by_name['Waypoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['AircraftLink'] = _AIRCRAFTLINK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Aircraft = _reflection.GeneratedProtocolMessageType('Aircraft', (_message.Message,), dict(
  DESCRIPTOR = _AIRCRAFT,
  __module__ = 'mavProxyLink_pb2'
  # @@protoc_insertion_point(class_scope:mav.Aircraft)
  ))
_sym_db.RegisterMessage(Aircraft)

Waypoints = _reflection.GeneratedProtocolMessageType('Waypoints', (_message.Message,), dict(
  DESCRIPTOR = _WAYPOINTS,
  __module__ = 'mavProxyLink_pb2'
  # @@protoc_insertion_point(class_scope:mav.Waypoints)
  ))
_sym_db.RegisterMessage(Waypoints)

Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
  DESCRIPTOR = _WAYPOINT,
  __module__ = 'mavProxyLink_pb2'
  # @@protoc_insertion_point(class_scope:mav.Waypoint)
  ))
_sym_db.RegisterMessage(Waypoint)

AircraftLink = _reflection.GeneratedProtocolMessageType('AircraftLink', (_message.Message,), dict(
  DESCRIPTOR = _AIRCRAFTLINK,
  __module__ = 'mavProxyLink_pb2'
  # @@protoc_insertion_point(class_scope:mav.AircraftLink)
  ))
_sym_db.RegisterMessage(AircraftLink)


# @@protoc_insertion_point(module_scope)
